/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sock_udp_UDPSocket */

#ifndef _Included_com_sock_udp_UDPSocket
#define _Included_com_sock_udp_UDPSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sock_udp_UDPSocket
 * Method:    createSocketC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sock_udp_UDPSocket_createSocketC
  (JNIEnv *, jobject);

/*
 * Class:     com_sock_udp_UDPSocket
 * Method:    sendC
 * Signature: (I[BIII)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_UDPSocket_sendC
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_sock_udp_UDPSocket
 * Method:    bindC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_UDPSocket_bindC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_udp_UDPSocket
 * Method:    closeC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_UDPSocket_closeC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sock_udp_UDPSocket
 * Method:    receiveC
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sock_udp_UDPSocket_receiveC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_udp_UDPSocket
 * Method:    connectC
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_UDPSocket_connectC
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
