/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sock_udp_DBLUDPSocket */

#ifndef _Included_com_sock_udp_DBLUDPSocket
#define _Included_com_sock_udp_DBLUDPSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sock_udp_DBLUDPSocket_init
  (JNIEnv *, jclass);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    createDeviceC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sock_udp_DBLUDPSocket_createDeviceC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    sendC
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_sendC
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    sendToC
 * Signature: (III[BII)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_sendToC
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    sendConnectC
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_sock_udp_DBLUDPSocket_sendConnectC
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    bindC
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sock_udp_DBLUDPSocket_bindC
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    bindAddrC
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_sock_udp_DBLUDPSocket_bindAddrC
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    receiveFromC
 * Signature: (IILcom/sock/udp/UDPPacket;I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_receiveFromC
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    mcastJoinC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_mcastJoinC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    mcastLeaveC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_mcastLeaveC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    deviceGetAttrsC
 * Signature: (ILcom/sock/udp/DeviceAttributes;)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_deviceGetAttrsC
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    deviceSetAttrsC
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_deviceSetAttrsC
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    deviceEnableC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_deviceEnableC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    shutdownC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_shutdownC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    unbindC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_unbindC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    sendDisconnectC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_sendDisconnectC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    closeC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_closeC
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
