/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sock_udp_DBLUDPSocket */

#ifndef _Included_com_sock_udp_DBLUDPSocket
#define _Included_com_sock_udp_DBLUDPSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_init
  (JNIEnv *, jclass);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    createSocketC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sock_udp_DBLUDPSocket_createSocketC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    sendC
 * Signature: (I[BIII)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_sendC
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    bindC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_bindC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    closeC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_closeC
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    receiveC
 * Signature: (ILcom/sock/udp/UDPPacket;I)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_receiveC
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     com_sock_udp_DBLUDPSocket
 * Method:    connectC
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_sock_udp_DBLUDPSocket_connectC
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
