/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sock_tcp_DBLTCPSocket */

#ifndef _Included_com_sock_tcp_DBLTCPSocket
#define _Included_com_sock_tcp_DBLTCPSocket
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
