/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_udp_UDPDemo */

#ifndef _Included_com_udp_UDPDemo
#define _Included_com_udp_UDPDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_udp_UDPDemo
 * Method:    sendMessage
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_udp_UDPDemo_sendMessage
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
