/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sock_tcp_KernelTCPSocket */

#ifndef _Included_com_sock_tcp_KernelTCPSocket
#define _Included_com_sock_tcp_KernelTCPSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    createSocketC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sock_tcp_KernelTCPSocket_createSocketC
  (JNIEnv *, jobject);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    bindC
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_bindC
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    listenC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_listenC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    acceptC
 * Signature: (ILcom/sock/tcp/KernelTCPSocket;)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_acceptC
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    connectC
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_connectC
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    sendC
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_sendC
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    receiveC
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sock_tcp_KernelTCPSocket_receiveC
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    setTimeoutReceiveC
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_setTimeoutReceiveC
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    setTimeoutSendC
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_setTimeoutSendC
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    setReuseAddrC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_setReuseAddrC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sock_tcp_KernelTCPSocket
 * Method:    closeC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_sock_tcp_KernelTCPSocket_closeC
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
